In [181]:
#Je cherche la corrélation des vues en fonction du mois, de l'année et de l'heure de publication
import pandas as pd

path = "FRvideos.csv"
df = pd.read_csv(path)
df.head()

video_id trending_date  \
0  Ro6eob0LrCY      17.14.11   
1  Yo84eqYwP98      17.14.11   
2  ceqntSXE-10      17.14.11   
3  WuTFI5qftCE      17.14.11   
4  ee6OFs8TdEg      17.14.11   

                                               title        channel_title  \
0           Malika LePen : Femme de Gauche - Trailer  Le Raptor Dissident   
1  LA PIRE PARTIE ft Le Rire Jaune, Pierre Croce,...              Le Labo   
2  DESSINS ANIMÉS FRANÇAIS VS RUSSES 2 - Daniil...      Daniil le Russe   
3                    PAPY GRENIER - METAL GEAR SOLID    Joueur Du Grenier   
4  QUI SAUTERA LE PLUS HAUT ? (VÉLO SKATE ROLLER ...    Aurelien Fontenoy   

   category_id              publish_time  \
0           24  2017-11-13T17:32:55.000Z   
1           24  2017-11-12T15:00:02.000Z   
2           23  2017-11-13T17:00:38.000Z   
3           20  2017-11-12T17:00:02.000Z   
4           17  2017-11-13T16:30:03.000Z   

                                                tags   views  likes  dislikes  \
0  Raptor"|"Dissident"|"Expliquez"|"moi"|"cette"|...  212702  29282      1108   
1                                             [none]  432721  14053       576   
2      cartoon"|"pokémon"|"école"|"ours"|"мультфильм  482153  76203       477   
3  Papy grenier"|"Metal Gear Solid"|"PS1"|"Tirage...  925222  85016       550   
4  vélo"|"vtt"|"bmx"|"freestyle"|"bike"|"mtb"|"di...  141695   8091        72   

   comment_count                                  thumbnail_link  \
0           3817  https://i.ytimg.com/vi/Ro6eob0LrCY/default.jpg   
1           1161  https://i.ytimg.com/vi/Yo84eqYwP98/default.jpg   
2           9580  https://i.ytimg.com/vi/ceqntSXE-10/default.jpg   
3           4303  https://i.ytimg.com/vi/WuTFI5qftCE/default.jpg   
4            481  https://i.ytimg.com/vi/ee6OFs8TdEg/default.jpg   

   comments_disabled  ratings_disabled  video_error_or_removed  \
0              False             False                   False   
1              False             False                   False   
2              False             False                   False   
3              False             False                   False   
4              False             False                   False   

                                         description  
0  Dimanche.\n18h30.\nSoyez présents pour la vidé...  
1  Le jeu de société: https://goo.gl/hhG1Ta\n\nGa...  
2  Une nouvelle dose de dessins animés français e...  
3  Nouvel ,épisode de Papy Grenier ! Ce mois-ci o...  
4  Sauts à plus de 4 mètres de haut dans un tramp...

In [182]:
datetime_time = pd.to_datetime(df['publish_time'])
df["hour"] = datetime_time.dt.hour
df["month"] = datetime_time.dt.month
df["year"] = datetime_time.dt.year
df.head()

video_id trending_date  \
0  Ro6eob0LrCY      17.14.11   
1  Yo84eqYwP98      17.14.11   
2  ceqntSXE-10      17.14.11   
3  WuTFI5qftCE      17.14.11   
4  ee6OFs8TdEg      17.14.11   

                                               title        channel_title  \
0           Malika LePen : Femme de Gauche - Trailer  Le Raptor Dissident   
1  LA PIRE PARTIE ft Le Rire Jaune, Pierre Croce,...              Le Labo   
2  DESSINS ANIMÉS FRANÇAIS VS RUSSES 2 - Daniil...      Daniil le Russe   
3                    PAPY GRENIER - METAL GEAR SOLID    Joueur Du Grenier   
4  QUI SAUTERA LE PLUS HAUT ? (VÉLO SKATE ROLLER ...    Aurelien Fontenoy   

   category_id              publish_time  \
0           24  2017-11-13T17:32:55.000Z   
1           24  2017-11-12T15:00:02.000Z   
2           23  2017-11-13T17:00:38.000Z   
3           20  2017-11-12T17:00:02.000Z   
4           17  2017-11-13T16:30:03.000Z   

                                                tags   views  likes  dislikes  \
0  Raptor"|"Dissident"|"Expliquez"|"moi"|"cette"|...  212702  29282      1108   
1                                             [none]  432721  14053       576   
2      cartoon"|"pokémon"|"école"|"ours"|"мультфильм  482153  76203       477   
3  Papy grenier"|"Metal Gear Solid"|"PS1"|"Tirage...  925222  85016       550   
4  vélo"|"vtt"|"bmx"|"freestyle"|"bike"|"mtb"|"di...  141695   8091        72   

   comment_count                                  thumbnail_link  \
0           3817  https://i.ytimg.com/vi/Ro6eob0LrCY/default.jpg   
1           1161  https://i.ytimg.com/vi/Yo84eqYwP98/default.jpg   
2           9580  https://i.ytimg.com/vi/ceqntSXE-10/default.jpg   
3           4303  https://i.ytimg.com/vi/WuTFI5qftCE/default.jpg   
4            481  https://i.ytimg.com/vi/ee6OFs8TdEg/default.jpg   

   comments_disabled  ratings_disabled  video_error_or_removed  \
0              False             False                   False   
1              False             False                   False   
2              False             False                   False   
3              False             False                   False   
4              False             False                   False   

                                         description  hour  month  year  
0  Dimanche.\n18h30.\nSoyez présents pour la vidé...    17     11  2017  
1  Le jeu de société: https://goo.gl/hhG1Ta\n\nGa...    15     11  2017  
2  Une nouvelle dose de dessins animés français e...    17     11  2017  
3  Nouvel ,épisode de Papy Grenier ! Ce mois-ci o...    17     11  2017  
4  Sauts à plus de 4 mètres de haut dans un tramp...    16     11  2017

In [183]:
from sklearn.model_selection import train_test_split
x = df[["hour", "year","month"]]
y = df["views"]
X_train, X_test, y_train, y_test = train_test_split(x, y)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((30543, 3), (30543,), (10181, 3), (10181,))

In [184]:
from sklearn import linear_model
lm = linear_model.Ridge()
model = lm.fit(X_train, y_train)
model

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [185]:
#trop faible corrélation
model.score(X_test, y_test)

0.005401987454760726

In [186]:
model.coef_,model.intercept_

(array([-25722.90758021, 250123.70952712,  23101.95978886]),
 -504006506.96497035)

In [187]:
x = df[["likes", "dislikes","comment_count"]]
y = df["views"]
X_train, X_test, y_train, y_test = train_test_split(x, y, random_state=42,test_size=0.30)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((28506, 3), (28506,), (12218, 3), (12218,))

In [188]:
lm = linear_model.LinearRegression()
model = lm.fit(X_train, y_train)
model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [189]:
model.score(X_test, y_test)

0.8395803759803655

In [190]:
model.coef_,model.intercept_

(array([ 18.00740549,  64.80274795, -36.75346572]), 126676.11989696015)

In [196]:
prediction = model.predict(X_test)
prediction

array([158747.81739201, 127438.36068186, 162907.28488796, ...,
       139284.63984862, 131907.65310128, 129587.19174664])

##############

In [199]:
# corrélation de la température en fonction du niveau d'ensoleillement, et la température à 9:00 et 15:00
import pandas as pd

path = "weatherAUS.csv"
df = pd.read_csv(path)
df.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2  2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
3  2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
4  2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity3pm  Pressure9am  \
0           W           44.0          W  ...        22.0       1007.7   
1         WNW           44.0        NNW  ...        25.0       1010.6   
2         WSW           46.0          W  ...        30.0       1007.6   
3          NE           24.0         SE  ...        16.0       1017.6   
4           W           41.0        ENE  ...        33.0       1010.8   

   Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  RISK_MM  \
0       1007.1       8.0       NaN     16.9     21.8         No      0.0   
1       1007.8       NaN       NaN     17.2     24.3         No      0.0   
2       1008.7       NaN       2.0     21.0     23.2         No      0.0   
3       1012.8       NaN       NaN     18.1     26.5         No      1.0   
4       1006.0       7.0       8.0     17.8     29.7         No      0.2   

   RainTomorrow  
0            No  
1            No  
2            No  
3            No  
4            No  

[5 rows x 24 columns]

In [200]:
import numpy as np
from sklearn.impute import SimpleImputer
model = SimpleImputer(missing_values=np.nan, strategy='mean')
df.iloc[:,3] =  model.fit_transform(df.iloc[:,2].values.reshape(-1,1))
df.iloc[:,6] =  model.fit_transform(df.iloc[:,2].values.reshape(-1,1))
df.iloc[:,19] =  model.fit_transform(df.iloc[:,2].values.reshape(-1,1))
df.iloc[:,20] =  model.fit_transform(df.iloc[:,2].values.reshape(-1,1))
df.isna().sum()

Date                 0
Location             0
MinTemp            637
MaxTemp              0
Rainfall          1406
Evaporation      60843
Sunshine             0
WindGustDir       9330
WindGustSpeed     9270
WindDir9am       10013
WindDir3pm        3778
WindSpeed9am      1348
WindSpeed3pm      2630
Humidity9am       1774
Humidity3pm       3610
Pressure9am      14014
Pressure3pm      13981
Cloud9am         53657
Cloud3pm         57094
Temp9am              0
Temp3pm              0
RainToday         1406
RISK_MM              0
RainTomorrow         0
dtype: int64

In [205]:
df["Sunshine"], df["Temp9am"], df["Temp3pm"]

(0         13.4
 1          7.4
 2         12.9
 3          9.2
 4         17.5
 5         14.6
 6         14.3
 7          7.7
 8          9.7
 9         13.1
 10        13.4
 11        15.9
 12        15.9
 13        12.6
 14         9.8
 15        14.1
 16        13.5
 17        11.2
 18         9.8
 19        11.5
 20        17.1
 21        20.5
 22        15.3
 23        12.6
 24        16.2
 25        16.9
 26        20.1
 27        19.7
 28        12.5
 29        12.0
           ... 
 142163    14.3
 142164     9.3
 142165     8.0
 142166    12.7
 142167     9.4
 142168     5.4
 142169     5.6
 142170     1.5
 142171     3.8
 142172     4.5
 142173     4.9
 142174     1.2
 142175     0.5
 142176     4.0
 142177     3.4
 142178     3.2
 142179     2.4
 142180     5.1
 142181     2.5
 142182     2.3
 142183     2.6
 142184     5.2
 142185     6.4
 142186     8.0
 142187     7.4
 142188     3.5
 142189     2.8
 142190     3.6
 142191     5.4
 142192     7.8
 Name: Sunshine, Length:

In [170]:
x = df[["Temp9am","Temp3pm", "Sunshine"]]
y = df["MaxTemp"]
X_train, X_test, y_train, y_test = train_test_split(x, y, random_state=42,test_size=0.30)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((99535, 3), (99535,), (42658, 3), (42658,))

In [171]:
lm = linear_model.Lasso()
model = lm.fit(X_train, y_train)
model

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [172]:
model.score(X_test, y_test)

0.9993995051326154

In [173]:
model.coef_,model.intercept_

(array([0.97549543, 0.        , 0.        ]), 0.29834396066157787)

In [174]:
prediction = model.predict(X_test)
prediction

array([ 7.22436154, 13.17488369,  9.27290195, ..., 14.44302775,
        9.76064967, 10.93124419])